[project]
name = "sed-minitorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hypothesis>=6.168.0",
    "networkx>=3.6.1",
    "numba>=0.67.0",
    "plotly>=7.1.0",
    "pydot>=4.0.1",
    "pytest>=9.1.1",
    "streamlit>=1.64.0",
    "streamlit-ace>=0.1.1",
    "torch>=2.14.0",
    "typing>=3.10.0.0",
]
